Update Installer

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -52,7 +52,7 @@ _mainScript_() {
 	read -q "res?Would you like to create XDG_DIRS? [y/N] "
     echo ""
     [[ $res == "y" ]] && {
-		if [ ! -e $HOME/.config/user-dirs.dirs ]; then
+		if [ ! -e "$HOME"/.config/user-dirs.dirs ]; then
 			xdg-user-dirs-update
 			echo "Creating xdg-user-dirs"
 		else
@@ -77,7 +77,7 @@ _mainScript_() {
 	fi
 
 	logo "Installation Finished!"
-	command rm -rf $HOME/.tmux $HOME/dotfiles/{Installer,LICENSE.txt,CHANGELOG,README.md}
+	command rm -rf "$HOME"/.tmux "$HOME"/dotfiles/{Installer,LICENSE.txt,CHANGELOG,README.md}
 	printf "%sReboot is necessary, then choose bspwm in your login manager and login.%s\n" "${BLD}" "${CNC}"
 	printf "%s%sRun dotup command to update configs anytime.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
 
@@ -93,8 +93,8 @@ _mainScript_() {
 
 	# Cleanup
 	for file in $HOME/{.tmux,.rustup,.xsession-*} $HOME/dotfiles/{Installer,LICENSE.txt,CHANGELOG,README.md}; do
-        if [ -e $file ]; then
-            rm -rf $file    
+        if [ -e "$file" ]; then
+            rm -rf "$file"    
         fi
     done
 
@@ -131,7 +131,7 @@ logo() {
 
 ##--> Check if the package is already installed or not <--##
 is_installed() {
-	pacman -Qi $1 &>/dev/null
+	pacman -Qi "$1" &>/dev/null
 	return $?
 }
 
@@ -140,8 +140,8 @@ install_pkg() {
 	logo "Installing Packages..."
 	printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
 	for package in "${dependencies[@]}"; do
-		if ! is_installed $package; then
-			sudo pacman -S $package --noconfirm
+		if ! is_installed "$package"; then
+			sudo pacman -S "$package" --noconfirm
 			printf "\n"
 		else
 			printf '%s✓ %s is already installed on your system!%s\n' "${CGR}" "$package" "${CNC}"
@@ -160,9 +160,9 @@ install_yay() {
 		sleep 1
 		printf "%s%s→ Installing YAY..%s\n\n" "${BLD}" "${CYE}" "${CNC}"
 		git clone --quiet https://aur.archlinux.org/yay.git
-		cd yay
+		cd yay || exit
 		makepkg -si
-		cd $HOME
+		cd "$HOME" || exit
 		rm -rf yay
 	else
 		printf "%s%s✓ YAY is already installed on your system%s\n" "${BLD}" "${CGR}" "${CNC}"
@@ -177,21 +177,21 @@ install_eww() {
 
 	if ! is_installed paru; then
 		printf "%s%sInstalling paru%s\n" "${BLD}" "${CBL}" "${CNC}"
-		cd
+		cd || exit
 		git clone https://aur.archlinux.org/paru-bin.git
-		cd paru-bin
+		cd paru-bin || exit
 		makepkg -si --noconfirm
-		cd
+		cd || exit
 	else
 		printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 	fi
 
 	if ! is_installed eww; then 
 		printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
-		cd
+		cd || exit
 		paru -S eww --skipreview --noconfirm
 		rm -rf {paru-bin,.cargo,.rustup}
-		rm -rf $HOME/.cache/paru/clone/eww
+		rm -rf "$HOME"/.cache/paru/clone/eww
 	else
 		printf "\n%s%sEww is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 	fi
@@ -206,7 +206,7 @@ setup_rice() {
 	[ -d ~/dotfiles ] && rm -rf ~/dotfiles
 	printf "→ Cloning gh0stzk's rice. (adityastomar67 fork)\n\n"
 
-	cd $HOME && git clone --quiet --depth=1 https://github.com/adityastomar67/dots.git $HOME/dotfiles
+	cd "$HOME" && git clone --quiet --depth=1 https://github.com/adityastomar67/dots.git "$HOME/dotfiles"
 	printf "%s%s✓ Configuration Cloned to $HOME/dotfiles.%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
@@ -221,46 +221,40 @@ setup_rice() {
 	fi
 
 	# Backing up the .config files
-	[ -d $HOME/.config ] && cd $HOME/.config
+	[ -d "$HOME"/.config ] && cd "$HOME"/.config || exit
 	for file in $(command ls ~/dotfiles/config/); do
 		if [ -L "$file" ]; then
 			command rm -rf "$file"
 			printf "%s✗ $file is a symlink and removed%s\n" "${CRE}" "${CNC}"
-			sleep 1
 		elif [ -d "$file" ]; then
 			command mv -f "$file" "$backup_folder/${file}_$date"
 			printf "%s✓ $file folder backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
-			sleep 1
 		elif [ -f "$file" ]; then
 			command mv -f "$file" "$backup_folder/${file}_$date"
 			printf "%s✓ $file file backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
-			sleep 1
 		else
 			printf "%s✗ $file not found!%s\n" "${CRE}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 
 	# Backing up the local bin files
-	if [ -d $HOME/.local/bin ]; then
-		cd $HOME/.local/bin
+	if [ -d "$HOME"/.local/bin ]; then
+		cd "$HOME"/.local/bin || exit
 		for file in $(command ls ~/dotfiles/misc/bin/); do
 			if [ -L "$file" ]; then
 				command rm -rf "$file"
 				printf "%s✗ $file is a symlink and removed%s\n" "${CRE}" "${CNC}"
-				sleep 1
 			elif [ -d "$file" ]; then
 				command mv -f "$file" "$backup_folder/${file}_$date"
 				printf "%s✓ $file folder backed up successfully at $backup_folder/bin/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
 			elif [ -f "$file" ]; then
 				command mv -f "$file" "$backup_folder/${file}_$date"
 				printf "%s✓ $file file backed up successfully at $backup_folder/bin/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
 			else
 				printf "%s✗ $file not found!%s\n" "${CRE}" "${CNC}"
-				sleep 1
 			fi
+			sleep 1
 		done
 	else
 		printf "%s✗ $HOME/.local/bin folder not found!%s\n" "${CRE}" "${CNC}"
@@ -268,25 +262,22 @@ setup_rice() {
 	fi
 
 	# Backing up all the asciiarts
-	if [ -d $HOME/.local/share/asciiart ]; then
-		cd $HOME/.local/share/asciiart
+	if [ -d "$HOME"/.local/share/asciiart ]; then
+		cd "$HOME"/.local/share/asciiart || exit
 		for file in $(command ls ~/dotfiles/misc/asciiart/); do
 			if [ -L "$file" ]; then
 				command rm -rf "$file"
 				printf "%s✗ $file is a symlink and removed%s\n" "${CRE}" "${CNC}"
-				sleep 1
 			elif [ -d "$file" ]; then
 				command mv -f "$file" "$backup_folder/${file}_$date"
 				printf "%s✓ $file folder backed up successfully at $backup_folder/ascii/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
 			elif [ -f "$file" ]; then
 				command mv -f "$file" "$backup_folder/${file}_$date"
 				printf "%s✓ $file file backed up successfully at $backup_folder/ascii/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
 			else
 				printf "%s✗ $file not found!%s\n" "${CRE}" "${CNC}"
-				sleep 1
 			fi
+			sleep 1
 		done
 	else
 		printf "%s✗ $HOME/.local/share/asciiart folder not found!%s\n" "${CRE}" "${CNC}"
@@ -317,57 +308,53 @@ setup_rice() {
 
 	# Linking the .config files
 	for conf in $(command ls ~/dotfiles/config/); do
-		ln -s ~/dotfiles/config/$conf ~/.config/$conf
+		ln -s ~/dotfiles/config/"$conf" ~/.config/"$conf"
 		if [ $? -eq 0 ]; then
 			printf "%s%s→ %s folder linked succesfully!%s\n" "${BLD}" "${CGR}" "${conf}" "${CNC}"
-			sleep 1
 		else
 			printf "%s%s✗ %s failed to been linked, you must do it manually%s\n" "${BLD}" "${CRE}" "${conf}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 
 	# Linking the local bin files
 	for file in $(command ls ~/dotfiles/misc/bin/); do
-		ln -s ~/dotfiles/misc/bin/$file ~/.local/bin/$file
+		ln -s ~/dotfiles/misc/bin/"$file" ~/.local/bin/"$file"
 		if [ $? -eq 0 ]; then
 			printf "%s%s→ %s linked succesfully!%s\n" "${BLD}" "${CGR}" "${file}" "${CNC}"
-			sleep 1
 		else
 			printf "%s%s✗ %s failed to been linked, you must do it manually%s\n" "${BLD}" "${CRE}" "${file}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 
 	# Linking all the applications
 	for art in ~/dotfiles/misc/applications/*; do
-		command cp -R ${art} ~/.local/share/applications/
+		command cp -R "${art}" ~/.local/share/applications/
 		if [ $? -eq 0 ]; then
 			printf "%s%s→ %s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${art}" "${CNC}"
-			sleep 1
 		else
 			printf "%s%s✗ %s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${art}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 
 	# Linking ascii art for terminal bling
 	for art in $(command ls ~/dotfiles/misc/asciiart/); do
-		ln -s ~/dotfiles/misc/asciiart/$art ~/.local/share/asciiart/$art
+		ln -s ~/dotfiles/misc/asciiart/"$art" ~/.local/share/asciiart/"$art"
 		if [ $? -eq 0 ]; then
 			printf "%s%s→ %s folder linked succesfully!%s\n" "${BLD}" "${CGR}" "${art}" "${CNC}"
-			sleep 1
 		else
 			printf "%s%s✗ %s failed to been linked, you must do it manually%s\n" "${BLD}" "${CRE}" "${art}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 
 	printf "\n\n%s%s✓ Files copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	logo "Configuring Tmux"
-	ln -s $HOME/dotfiles/home/.tmux.conf $HOME/.tmux.conf && printf "%s→ Tmux conf linked succesfully!%s\n" "${CGR}" "${CNC}" && sleep 1
+	ln -s "$HOME"/dotfiles/home/.tmux.conf "$HOME"/.tmux.conf && printf "%s→ Tmux conf linked succesfully!%s\n" "${CGR}" "${CNC}" && sleep 1
 	sleep 1
 	printf "\n\n%s%s✓ Done succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
@@ -375,25 +362,24 @@ setup_rice() {
 	logo "Caching fonts..."
 	# Copying all the fonts
 	for font in ~/dotfiles/misc/fonts/*; do
-		command cp -R ${font} ~/.local/share/fonts/
+		command cp -R "${font}" ~/.local/share/fonts/
 		if [ $? -eq 0 ]; then
 			printf "%s%s→ %s copied succesfully!%s\n" "${BLD}" "${CGR}" "${font}" "${CNC}"
-			sleep 1
 		else
 			printf "%s%s✗ %s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${font}" "${CNC}"
-			sleep 1
 		fi
+		sleep 1
 	done
 	fc-cache -rv >/dev/null 2>&1
 	printf "\n\n%s%s✓ Fonts copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	logo "Configuring Suckless Tools"
-	[ -d $HOME/.local/bin/st ] && cd $HOME/.local/bin/st
+	[ -d "$HOME"/.local/bin/st ] && cd "$HOME"/.local/bin/st || exit
 	printf "%s→ Installing ST Terminal%s\n" "${CYE}" "${CNC}"
 	sudo make clean install >/dev/null 2>&1
 
-	[ -d $HOME/.local/bin/dmenu ] && cd $HOME/.local/bin/dmenu
+	[ -d "$HOME"/.local/bin/dmenu ] && cd "$HOME"/.local/bin/dmenu || exit
 	printf "\n%s→ Installing Dmenu%s\n" "${CYE}" "${CNC}"
 	sudo make clean install >/dev/null 2>&1
 
@@ -405,44 +391,58 @@ setup_rice() {
 firefox_css() {
 	logo "Installing Firefox CSS..."
 	if is_installed firefox; then
-		firefox &
-		sleep 5
-		pkill -f firefox
-		sleep 2
+		if [ ! -d "$HOME/.mozilla/firefox" ]; then
+			firefox &
+			sleep 5
+			pkill -f firefox
+			sleep 2
+		fi
 
-		for folder in chrome; do
-			if [ -d "$HOME"/.mozilla/firefox/*.default-release/$folder ]; then
-				mv "$HOME"/.mozilla/firefox/*.default-release/$folder "$backup_folder"/${folder}_$date
-				printf "%s✓ $file folder backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
+		# for folder in chrome; do
+		# 	if [ -d "$HOME/.mozilla/firefox/*.default-release/$folder" ]; then
+		# 		mv "$HOME/.mozilla/firefox/*.default-release/$folder" "$backup_folder/$folder_$date"
+		# 		printf "%s✓ $file folder backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
+		# 		sleep 1
+		# 	else
+		# 		printf "%s✗ The folder $folder does not exist in $HOME/.mozilla/firefox/%s\n" "${CRE}" "${CNC}"
+		# 		sleep 1
+		# 	fi
+		# done
+
+		# for file in user.js; do
+		# 	if [ -e "$HOME/.mozilla/firefox/*.default-release/$file" ]; then
+		# 		mv "$HOME/.mozilla/firefox/*.default-release/$file" "$backup_folder/$file_$date"
+		# 		printf "%s✓ $file file backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
+		# 		sleep 1
+		# 	else
+		# 		printf "%s✗ The file $file does not exist in $HOME/.mozilla/firefox/%s\n" "${CRE}" "${CNC}"
+		# 		sleep 1
+		# 	fi
+		# done
+
+		for archive in $(command ls ~/dotfiles/misc/firefox/); do
+			if [ -e "$HOME/.mozilla/firefox/*.default-release/$archive" ]; then
+				mv "$HOME/.mozilla/firefox/*.default-release/$archive" "$backup_folder/$archive_$date"
+				if [ $? -eq 0 ]; then
+					printf "%s✓ $archive backed up successfully at $backup_folder/config/${archive}_$date%s\n" "${CGR}" "${CNC}"
+				else
+					printf "%s%s✗ %s failed to be backed up, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archive}" "${CNC}"
+				fi
 			else
-				printf "%s✗The folder $folder does not exist in $HOME/.mozilla/firefox/%s\n" "${CRE}" "${CNC}"
-				sleep 1
+				printf "%s✗ $archive does not exist in $HOME/.mozilla/firefox/%s\n" "${CRE}" "${CNC}"
 			fi
+			sleep 1
 		done
 
-		for file in user.js; do
-			if [ -e "$HOME"/.mozilla/firefox/*.default-release/$file ]; then
-				mv "$HOME"/.mozilla/firefox/*.default-release/$file "$backup_folder"/${file}_$date
-				printf "%s✓ $file file backed up successfully at $backup_folder/config/${file}_$date%s\n" "${CGR}" "${CNC}"
-				sleep 1
-			else
-				printf "%s✗The file $file does not exist in $HOME/.mozilla/firefox/%s\n" "${CRE}" "${CNC}"
-				sleep 1
-			fi
-		done
-
-		for archive in ~/dotfiles/misc/firefox/*; do
-			cp -R "${archive}" ~/.mozilla/firefox/*.default-release/
+		for archive in $(command ls ~/dotfiles/misc/firefox/*); do
+			cp -R "$HOME/dotfiles/misc/firefox/$archive" "$HOME/.mozilla/firefox/*.default-release/"
 			if [ $? -eq 0 ]; then
-				printf "%s%s✓ Firefox CSS Done!!%s\n" "${BLD}" "${CGR}" "${CNC}"
-				sleep 1
+				printf "%s%s✓ $archive copied!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 			else
-				printf "%s✗ Firefox CSS cannot be Done!!%s\n" "${CRE}" "${CNC}"				
-				sleep 1
+				printf "%s✗ $archive is not copied!!%s\n" "${CRE}" "${CNC}"				
 			fi
+			sleep 1
 		done
-
 	else
 		printf "%s✗ Firefox is not instaleed on the system%s\n" "${CRE}" "${CNC}"
 		sleep 2
