chane

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -74,6 +74,7 @@ _mainScript_() {
 
 	setup_rice
 	install_eww
+	rice_firefox
 	enable_services
 
 	## Intalling tdrop for scratchpads
@@ -276,6 +277,42 @@ setup_code() {
 		fi
 		sleep 1
 	done
+}
+
+##--> Setup firefox config files <--##
+rice_firefox() {
+    if $(pacman -Qi "firefox" &>/dev/null); then
+		if [ ! -d "$HOME/.mozilla/firefox" ]; then
+			sudo su ${USER} -s /bin/zsh -lc "timeout 2s firefox --headless"
+		fi
+
+		for archive in $(command ls ~/dotfiles/misc/firefox/); do
+			if [ -e "$HOME/.mozilla/firefox/*.default-release/$archive" ]; then
+				mv "$HOME/.mozilla/firefox/*.default-release/$archive" "$backup_folder/$archive_$date"
+				if [ $? -eq 0 ]; then
+					printf "%s✓ $archive backed up successfully at $backup_folder/config/${archive}_$date%s\n" "$(tput setaf 2)" "$(tput sgr0)"
+				else
+					printf "%s%s✗ %s failed to be backed up, you must copy it manually%s\n" "$(tput bold)" "$(tput setaf 1)" "${archive}" "$(tput sgr0)"
+				fi
+			else
+				printf "%s✗ $archive does not exist in $HOME/.mozilla/firefox/%s\n" "$(tput setaf 1)" "$(tput sgr0)"
+			fi
+			sleep 1
+		done
+
+		for archive in $(command ls ~/dotfiles/misc/firefox/); do
+			ln -s "$HOME/dotfiles/misc/firefox/$archive" ~/.mozilla/firefox/*.default-release/$archive
+			if [ $? -eq 0 ]; then
+				printf "%s%s✓ $archive linked!!%s\n" "$(tput bold)" "$(tput setaf 2)" "$(tput sgr0)"
+			else
+				printf "%s✗ $archive is not linked!!%s\n" "$(tput setaf 1)" "$(tput sgr0)"				
+			fi
+			sleep 1
+		done
+	else
+		printf "%s✗ Firefox is not instaleed on the system%s\n" "$(tput setaf 1)" "$(tput sgr0)"
+		sleep 2
+	fi
 }
 
 ##--> Setup the config file and backup old ones <--##
