Update Installer

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -51,15 +51,17 @@ _mainScript_() {
 	enable_services
 
 	# Mozilla Firefox rice
-	if [ -d $HOME/.mozilla/firefox/*.default-release/ ]; then
-		mv $HOME/.mozilla/firefox/*.default-release/chrome $backup_folder/firefox_$date/
-		cp -R $HOME/dotfiles/misc/firefox/chrome $HOME/.mozilla/firefox/*.default-release/
-		cp -R $HOME/dotfiles/misc/firefox/user.js $HOME/.mozilla/firefox/*.default-release/
+	logo "Installing Firefox CSS..."
+	if [ -d "$HOME/.mozilla/firefox/*.default-release/" ]; then
+		mv "$HOME/.mozilla/firefox/*.default-release/chrome" "$backup_folder/firefox_$date/"
+		cp -R "$HOME/dotfiles/misc/firefox/chrome" "$HOME/.mozilla/firefox/*.default-release/"
+		cp -R "$HOME/dotfiles/misc/firefox/user.js" "$HOME/.mozilla/firefox/*.default-release/"
 	fi
+	printf "%s%s✓ Firefox Done!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	sleep 2
 
 	# Changing shell to Zsh
 	chsh -s /usr/bin/zsh
-	zsh
 
 	logo "Installation Finished!"
 	printf "%sReboot is necessary, then choose bspwm in your login manager and login.%s\n" "${BLD}" "${CNC}"
@@ -74,6 +76,8 @@ _mainScript_() {
 		esac
 	done
 	sleep 5
+
+	zsh
 }
 
 ##--> Logo <--##
@@ -147,7 +151,7 @@ install_yay() {
 install_eww() {
 
 	logo "Installing EWW..."
-	if ! is_installed "eww"; then
+	if ! is_installed eww; then
 		printf "%s%sNow eww will be downloaded, compiled and installed.. this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
 		cd $HOME
 		sudo pacman -S rustup gtk3
@@ -258,7 +262,7 @@ setup_rice() {
 	[ -L ~/.tmux.conf ] && rm -rf ~/.tmux.conf ||
 		[ -f ~/.tmux.conf ] && mv ~/.tmux.conf $backup_folder/.tmux.conf-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
 
-	printf "%s%s✓ Backup Done!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n\n%s%s✓ Backup Done!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	##--> Copy the Files <--##
@@ -288,7 +292,7 @@ setup_rice() {
 	for archive in $(command ls ~/dotfiles/misc/bin/); do
 		ln -s ~/dotfiles/misc/bin/$archive ~/.local/bin/$archive
 		if [ $? -eq 0 ]; then
-			printf "%s%s→ %s folder linked succesfully!%s\n" "${BLD}" "${CGR}" "${archive}" "${CNC}"
+			printf "%s%s→ %s linked succesfully!%s\n" "${BLD}" "${CGR}" "${archive}" "${CNC}"
 			sleep 1
 		else
 			printf "%s%s✗ %s failed to been linked, you must do it manually%s\n" "${BLD}" "${CRE}" "${archive}" "${CNC}"
@@ -308,18 +312,6 @@ setup_rice() {
 		fi
 	done
 
-	# Copying all the fonts
-	for archive in ~/dotfiles/misc/fonts/*; do
-		command cp -R ${archive} ~/.local/share/fonts/
-		if [ $? -eq 0 ]; then
-			printf "%s%s→ %s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archive}" "${CNC}"
-			sleep 1
-		else
-			printf "%s%s✗ %s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archive}" "${CNC}"
-			sleep 1
-		fi
-	done
-
 	# Linking ascii art for terminal bling
 	for archive in $(command ls ~/dotfiles/misc/asciiart/); do
 		ln -s ~/dotfiles/misc/asciiart/$archive ~/.local/share/asciiart/$archive
@@ -332,18 +324,29 @@ setup_rice() {
 		fi
 	done
 
-	printf "%s%s✓ Files copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n\n%s%s✓ Files copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	logo "Configuring ZSH & Tmux"
 	ln -s $HOME/dotfiles/home/.tmux.conf $HOME/.tmux.conf && printf "%s→ Tmux conf linked succesfully!%s\n" "${CGR}" "${CNC}" && sleep 1
 	ln -s $HOME/dotfiles/home/.zshrc $HOME/.zshrc && printf "%s→ Zshrc linked succesfully!%s\n" "${CGR}" "${CNC}" && sleep 1
-	printf "%s%s✓ Done succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n\n%s%s✓ Done succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	logo "Caching fonts..."
+	# Copying all the fonts
+	for archive in ~/dotfiles/misc/fonts/*; do
+		command cp -R ${archive} ~/.local/share/fonts/
+		if [ $? -eq 0 ]; then
+			printf "%s%s→ %s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archive}" "${CNC}"
+			sleep 1
+		else
+			printf "%s%s✗ %s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archive}" "${CNC}"
+			sleep 1
+		fi
+	done
 	fc-cache -rv >/dev/null 2>&1
-	printf "%s%s✓ Fonts copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n\n%s%s✓ Fonts copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 
 	logo "Configuring Suckless Tools"
@@ -352,10 +355,10 @@ setup_rice() {
 	sudo make clean install >/dev/null 2>&1
 
 	[ -d $HOME/.local/bin/dmenu ] && cd $HOME/.local/bin/dmenu
-	printf "%s→ Installing Dmenu%s\n" "${CYE}" "${CNC}"
+	printf "\n%s→ Installing Dmenu%s\n" "${CYE}" "${CNC}"
 	sudo make clean install >/dev/null 2>&1
 
-	printf "%s%s✓ Done succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	printf "\n\n%s%s✓ Done succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 }
 
@@ -364,12 +367,16 @@ enable_services() {
 	logo "Enabling services..."
 	if is_installed lightdm; then
 		sudo systemctl enable lightdm -f >/dev/null 2>&1
-		printf '%s✓ LightDM services enabled on your system!%s\n' "${CGR}" "${CNC}"
+		printf '%s✓ LightDM services enabled on your system!%s\n\n' "${CGR}" "${CNC}"
 		sleep 2
 	fi
-	sudo systemctl enable mpd.service
-	sudo systemctl start mpd.service
-	printf "%s%s✓ Services enabled!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	if is_installed mpd; then
+		sudo systemctl enable mpd.service >/dev/null 2>&1
+		sudo systemctl start mpd.service >/dev/null 2>&1
+		printf '%s✓ Mpd services enabled on your system!%s\n\n' "${CGR}" "${CNC}"
+		sleep 2
+	fi
+	printf "\n%s%s✓ All required services enabled!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 	sleep 2
 }
 
