Fewer Updates

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -16,14 +16,14 @@ backup_folder=~/.RiceBackup
 date=$(date +%Y%m%d-%H%M%S)
 
 ##--> Dependecies for smoother experience <--##
-dependencies=(conky base-devel rustup pacman-contrib bspwm polybar sxhkd \
-			  alacritty brightnessctl dunst rofi lsd \
-			  jq polkit-gnome git playerctl mpd fzf \
-			  ncmpcpp geany ranger mpc picom xdotool tmux \
-			  feh ueberzug maim pamixer libwebp xdg-user-dirs xorg-xauth \
-			  webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme \
-			  ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels \
-			  zsh xorg-xsetroot xorg-xwininfo)
+dependencies=(conky base-devel rustup pacman-contrib bspwm polybar sxhkd
+	alacritty brightnessctl dunst rofi lsd
+	jq polkit-gnome git playerctl mpd fzf
+	ncmpcpp geany ranger mpc picom xdotool tmux
+	feh ueberzug maim pamixer libwebp xdg-user-dirs xorg-xauth
+	webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme
+	ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman
+	zsh xorg-xsetroot xorg-xwininfo)
 
 ##--> Check if it's running as root <--##
 if [ "$(id -u)" = 0 ]; then
@@ -52,25 +52,25 @@ _mainScript_() {
 	while true; do
 		read -rp "Do you want to create User Dirs? [y/N]: " yn
 		case $yn in
-			[Yy]*)
-				if [ ! -e "$HOME"/.config/user-dirs.dirs ]; then
-					echo "Creating xdg-user-dirs"
-					xdg-user-dirs-update
-				else
-					echo "user-dirs.dirs already exists"
-				fi
-				break	
+		[Yy]*)
+			if [ ! -e "$HOME"/.config/user-dirs.dirs ]; then
+				echo "Creating xdg-user-dirs"
+				xdg-user-dirs-update
+			else
+				echo "user-dirs.dirs already exists"
+			fi
+			break
 			;;
-			[Nn]*) break ;;
-			*) printf "✗ Error: just write 'y' or 'n'\n\n" ;;
+		[Nn]*) break ;;
+		*) printf "✗ Error: just write 'y' or 'n'\n\n" ;;
 		esac
 	done
-	sleep 2 
+	sleep 2
 
 	# Clean Neovim cache files
 	[ -d "$HOME/.local/share/nvim" ] && rm -rf "$HOME/.local/share/nvim"
 	[ -d "$HOME/.local/state/nvim" ] && rm -rf "$HOME/.local/state/nvim"
-	[ -d "$HOME/.cache/nvim" ]       && rm -rf "$HOME/.cache/nvim"
+	[ -d "$HOME/.cache/nvim" ] && rm -rf "$HOME/.cache/nvim"
 
 	setup_rice
 	install_eww
@@ -97,13 +97,13 @@ _mainScript_() {
 
 	# Cleanup
 	for file in $HOME/{.tmux,.rustup,.xsession-*,Installer,.vscode*,.bash_*} $HOME/dotfiles/{Installer,LICENSE.txt,CHANGELOG,README.md}; do
-        if [ -e "$file" ]; then
-            rm -rf "$file"    
-        fi
-    done
+		if [ -e "$file" ]; then
+			rm -rf "$file"
+		fi
+	done
 
 	chmod +x $HOME/.config/bspwm/scripts/*
-    chmod +x $HOME/.local/share/asciiart/*
+	chmod +x $HOME/.local/share/asciiart/*
 
 	logo "Installation Finished!"
 	printf "%sReboot is necessary, then choose bspwm in your login manager and login.%s\n" "${BLD}" "${CNC}"
@@ -198,10 +198,10 @@ install_eww() {
 		printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 	fi
 
-	if ! is_installed eww; then 
+	if ! is_installed eww; then
 		printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
 		cd || exit
-		paru -S eww-x11-git --skipreview --noconfirm
+		paru -S eww-x11 --skipreview --noconfirm
 		rm -rf {paru-bin,.cargo,.rustup}
 		rm -rf "$HOME"/.cache/paru/clone/eww
 	else
@@ -229,24 +229,24 @@ setup_code() {
 		--install-extension PKief.material-icon-theme \
 		--install-extension antfu.icons-carbon \
 		--install-extension zhuangtongfa.Material-theme
-    	# --install-extension octref.vetur@0.34.1 \
-    	# --install-extension s-nlf-fh.glassit \
-    	# --install-extension ms-vscode.cpptools \
-    	# --install-extension esbenp.prettier-vscode \
-    	# --install-extension ritwickdey.liveserver \
-    	# --install-extension ms-python.python \
-    	# --install-extension ms-python.vscode-pylance \
-    	# --install-extension moalamri.inline-fold \
-    	# --install-extension foxundermoon.shell-format \
-    	# --install-extension teabyii.ayu@0.20.2 \
-    	# --install-extension matklad.rust-analyzer@0.2.727 \
-    	# --install-extension GitHub.github-vscode-theme \
-    	# --install-extension vscodevim.vim \
-    	# --install-extension viktorqvarfordt.vscode-pitch-black-theme \
-    	# --install-extension EliverLara.andromeda \
-    	# --install-extension ms-vscode.sublime-keybindings@4.0.10 \
-    	# --install-extension Chouzz.vscode-better-align \
-    	# --install-extension iocave.customize-ui \
+	# --install-extension octref.vetur@0.34.1 \
+	# --install-extension s-nlf-fh.glassit \
+	# --install-extension ms-vscode.cpptools \
+	# --install-extension esbenp.prettier-vscode \
+	# --install-extension ritwickdey.liveserver \
+	# --install-extension ms-python.python \
+	# --install-extension ms-python.vscode-pylance \
+	# --install-extension moalamri.inline-fold \
+	# --install-extension foxundermoon.shell-format \
+	# --install-extension teabyii.ayu@0.20.2 \
+	# --install-extension matklad.rust-analyzer@0.2.727 \
+	# --install-extension GitHub.github-vscode-theme \
+	# --install-extension vscodevim.vim \
+	# --install-extension viktorqvarfordt.vscode-pitch-black-theme \
+	# --install-extension EliverLara.andromeda \
+	# --install-extension ms-vscode.sublime-keybindings@4.0.10 \
+	# --install-extension Chouzz.vscode-better-align \
+	# --install-extension iocave.customize-ui \
 
 	if [ -d "$HOME"/.config/Code/User ]; then
 		cd "$HOME"/.config/Code/User || exit
@@ -281,7 +281,7 @@ setup_code() {
 
 ##--> Setup firefox config files <--##
 rice_firefox() {
-    if $(pacman -Qi "firefox" &>/dev/null); then
+	if $(pacman -Qi "firefox" &>/dev/null); then
 		if [ ! -d "$HOME/.mozilla/firefox" ]; then
 			sudo su ${USER} -s /bin/zsh -lc "timeout 2s firefox --headless"
 		fi
@@ -305,7 +305,7 @@ rice_firefox() {
 			if [ $? -eq 0 ]; then
 				printf "%s%s✓ $archive linked!!%s\n" "$(tput bold)" "$(tput setaf 2)" "$(tput sgr0)"
 			else
-				printf "%s✗ $archive is not linked!!%s\n" "$(tput setaf 1)" "$(tput sgr0)"				
+				printf "%s✗ $archive is not linked!!%s\n" "$(tput setaf 1)" "$(tput sgr0)"
 			fi
 			sleep 1
 		done
@@ -507,20 +507,20 @@ setup_rice() {
 	printf "%s→ Installing ST Terminal%s\n" "${CYE}" "${CNC}"
 	sudo make clean install >/dev/null 2>&1
 	if [ $? -eq 0 ]; then
-			printf "%s%s✓ ST installed succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
-		else
-			printf "%s%s✗ Cannot install ST, you have to compile it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
-		fi
+		printf "%s%s✓ ST installed succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	else
+		printf "%s%s✗ Cannot install ST, you have to compile it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+	fi
 	sleep 1
 
 	[ -d "$HOME"/.local/bin/dmenu ] && cd "$HOME"/.local/bin/dmenu || exit
 	printf "%s→ Installing Dmenu%s\n" "${CYE}" "${CNC}"
 	sudo make clean install >/dev/null 2>&1
 	if [ $? -eq 0 ]; then
-			printf "%s%s✓ DMenu installed succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
-		else
-			printf "%s%s✗ Cannot install DMenu, you have to compile it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
-		fi
+		printf "%s%s✓ DMenu installed succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
+	else
+		printf "%s%s✗ Cannot install DMenu, you have to compile it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+	fi
 	sleep 1
 
 	logo "Extra Configs"
@@ -547,7 +547,7 @@ enable_services() {
 		printf '%s✓ LightDM services enabled on your system!%s\n\n' "${CGR}" "${CNC}"
 		sleep 2
 	fi
-	
+
 	if is_installed mpd; then
 		systemctl --user enable mpd.service >/dev/null 2>&1
 		systemctl --user start mpd.service >/dev/null 2>&1
